variables:
  VAULT_ROLE: "myproject-production"
read_secrets:
  image: alpine:latest
  before_script:
    - apk add -q jq curl vault
  script:
    # Check job's ref name
    - echo $CI_COMMIT_REF_NAME
    # and is this ref protected
    - echo $CI_COMMIT_REF_PROTECTED
    - echo $CI_JOB_JWT
    # Authenticate and get token. Token expiry time and other properties can be configured
    # when configuring JWT Auth - https://www.vaultproject.io/api/auth/jwt#parameters-1
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role={$VAULT_ROLE} jwt=$CI_JOB_JWT)"
    # Now use the VAULT_TOKEN to read the secret and store it 
    - AWSKEY="$(vault kv get -format=json secret/production/aws_key | jq '.data.data.pass')"
    # Use the secret
    - echo $AWSKEY
   # Now use the VAULT_TOKEN to read the secret and store it 
    - DBPASSWORD="$(vault kv get -format=json secret/production/aws_key | jq '.data.data.pass')"
    # Use the secret
    - echo $DBPASSWORD
    # end 
